/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProblemId = IDL.Nat;
export const ProblemType = IDL.Variant({
  'trialBalance' : IDL.Null,
  'cashFlowStatement' : IDL.Null,
  'balanceSheet' : IDL.Null,
  'journalEntry' : IDL.Null,
  'incomeStatement' : IDL.Null,
  'ledgerPostings' : IDL.Null,
});
export const Time = IDL.Int;
export const Problem = IDL.Record({
  'id' : ProblemId,
  'type' : ProblemType,
  'jsonInput' : IDL.Text,
  'solution' : IDL.Text,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({
  'studentId' : IDL.Opt(IDL.Text),
  'institution' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
});
export const CustomerMessageWithReply = IDL.Record({
  'id' : IDL.Nat,
  'adminReply' : IDL.Opt(IDL.Text),
  'sender' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : Time,
  'senderName' : IDL.Text,
});
export const QuizResult = IDL.Record({
  'id' : IDL.Nat,
  'topic' : IDL.Text,
  'total' : IDL.Nat,
  'wrongQuestionIds' : IDL.Vec(IDL.Nat),
  'score' : IDL.Nat,
  'timestamp' : Time,
});
export const QuizQuestion = IDL.Record({
  'id' : IDL.Nat,
  'topic' : IDL.Text,
  'question' : IDL.Text,
  'isAdminAdded' : IDL.Bool,
  'correctIndex' : IDL.Nat,
  'explanation' : IDL.Text,
  'optionA' : IDL.Text,
  'optionB' : IDL.Text,
  'optionC' : IDL.Text,
  'optionD' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAdminQuestion' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCustomerMessage' : IDL.Func([IDL.Nat], [], []),
  'deleteProblem' : IDL.Func([ProblemId], [], []),
  'deleteQuizQuestion' : IDL.Func([IDL.Nat], [], []),
  'findProblemsByKeyword' : IDL.Func([IDL.Text], [IDL.Vec(Problem)], ['query']),
  'findProblemsByType' : IDL.Func([ProblemType], [IDL.Vec(Problem)], ['query']),
  'forceClaimAdmin' : IDL.Func([], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomerMessages' : IDL.Func(
      [],
      [IDL.Vec(CustomerMessageWithReply)],
      ['query'],
    ),
  'getIsAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'getMyCustomerMessages' : IDL.Func(
      [],
      [IDL.Vec(CustomerMessageWithReply)],
      ['query'],
    ),
  'getProblem' : IDL.Func([ProblemId], [IDL.Vec(Problem)], ['query']),
  'getProblemHistory' : IDL.Func([], [IDL.Vec(Problem)], ['query']),
  'getQuizHistory' : IDL.Func([], [IDL.Vec(QuizResult)], ['query']),
  'getQuizQuestions' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(QuizQuestion)],
      ['query'],
    ),
  'getUserCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listProblemTypes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'registerUser' : IDL.Func([], [], []),
  'replyToCustomerMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveProblem' : IDL.Func([ProblemType, IDL.Text, IDL.Text], [], []),
  'saveQuizResult' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Vec(IDL.Nat)],
      [],
      [],
    ),
  'submitCustomerMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProblemId = IDL.Nat;
  const ProblemType = IDL.Variant({
    'trialBalance' : IDL.Null,
    'cashFlowStatement' : IDL.Null,
    'balanceSheet' : IDL.Null,
    'journalEntry' : IDL.Null,
    'incomeStatement' : IDL.Null,
    'ledgerPostings' : IDL.Null,
  });
  const Time = IDL.Int;
  const Problem = IDL.Record({
    'id' : ProblemId,
    'type' : ProblemType,
    'jsonInput' : IDL.Text,
    'solution' : IDL.Text,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'studentId' : IDL.Opt(IDL.Text),
    'institution' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
  });
  const CustomerMessageWithReply = IDL.Record({
    'id' : IDL.Nat,
    'adminReply' : IDL.Opt(IDL.Text),
    'sender' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : Time,
    'senderName' : IDL.Text,
  });
  const QuizResult = IDL.Record({
    'id' : IDL.Nat,
    'topic' : IDL.Text,
    'total' : IDL.Nat,
    'wrongQuestionIds' : IDL.Vec(IDL.Nat),
    'score' : IDL.Nat,
    'timestamp' : Time,
  });
  const QuizQuestion = IDL.Record({
    'id' : IDL.Nat,
    'topic' : IDL.Text,
    'question' : IDL.Text,
    'isAdminAdded' : IDL.Bool,
    'correctIndex' : IDL.Nat,
    'explanation' : IDL.Text,
    'optionA' : IDL.Text,
    'optionB' : IDL.Text,
    'optionC' : IDL.Text,
    'optionD' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAdminQuestion' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCustomerMessage' : IDL.Func([IDL.Nat], [], []),
    'deleteProblem' : IDL.Func([ProblemId], [], []),
    'deleteQuizQuestion' : IDL.Func([IDL.Nat], [], []),
    'findProblemsByKeyword' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Problem)],
        ['query'],
      ),
    'findProblemsByType' : IDL.Func(
        [ProblemType],
        [IDL.Vec(Problem)],
        ['query'],
      ),
    'forceClaimAdmin' : IDL.Func([], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomerMessages' : IDL.Func(
        [],
        [IDL.Vec(CustomerMessageWithReply)],
        ['query'],
      ),
    'getIsAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'getMyCustomerMessages' : IDL.Func(
        [],
        [IDL.Vec(CustomerMessageWithReply)],
        ['query'],
      ),
    'getProblem' : IDL.Func([ProblemId], [IDL.Vec(Problem)], ['query']),
    'getProblemHistory' : IDL.Func([], [IDL.Vec(Problem)], ['query']),
    'getQuizHistory' : IDL.Func([], [IDL.Vec(QuizResult)], ['query']),
    'getQuizQuestions' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(QuizQuestion)],
        ['query'],
      ),
    'getUserCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listProblemTypes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'registerUser' : IDL.Func([], [], []),
    'replyToCustomerMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveProblem' : IDL.Func([ProblemType, IDL.Text, IDL.Text], [], []),
    'saveQuizResult' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Vec(IDL.Nat)],
        [],
        [],
      ),
    'submitCustomerMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };