/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomerMessage {
  'id' : bigint,
  'sender' : Principal,
  'message' : string,
  'timestamp' : Time,
  'senderName' : string,
}
export interface Problem {
  'id' : ProblemId,
  'type' : ProblemType,
  'jsonInput' : string,
  'solution' : string,
  'timestamp' : Time,
}
export type ProblemId = bigint;
export type ProblemType = { 'trialBalance' : null } |
  { 'cashFlowStatement' : null } |
  { 'balanceSheet' : null } |
  { 'journalEntry' : null } |
  { 'incomeStatement' : null } |
  { 'ledgerPostings' : null };
export type Time = bigint;
export interface UserProfile {
  'studentId' : [] | [string],
  'institution' : [] | [string],
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteProblem' : ActorMethod<[ProblemId], undefined>,
  'findProblemsByKeyword' : ActorMethod<[string], Array<Problem>>,
  'findProblemsByType' : ActorMethod<[ProblemType], Array<Problem>>,
  'forceClaimAdmin' : ActorMethod<[], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerMessages' : ActorMethod<[], Array<CustomerMessage>>,
  'getIsAdmin' : ActorMethod<[], boolean>,
  'getProblem' : ActorMethod<[ProblemId], Array<Problem>>,
  'getProblemHistory' : ActorMethod<[], Array<Problem>>,
  'getUserCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listProblemTypes' : ActorMethod<[], Array<string>>,
  'registerUser' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveProblem' : ActorMethod<[ProblemType, string, string], undefined>,
  'submitCustomerMessage' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];