/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomerMessageWithReply {
  'id' : bigint,
  'adminReply' : [] | [string],
  'sender' : Principal,
  'message' : string,
  'timestamp' : Time,
  'senderName' : string,
}
export interface Problem {
  'id' : ProblemId,
  'type' : ProblemType,
  'jsonInput' : string,
  'solution' : string,
  'timestamp' : Time,
}
export type ProblemId = bigint;
export type ProblemType = { 'trialBalance' : null } |
  { 'cashFlowStatement' : null } |
  { 'balanceSheet' : null } |
  { 'journalEntry' : null } |
  { 'incomeStatement' : null } |
  { 'ledgerPostings' : null };
export interface QuizQuestion {
  'id' : bigint,
  'topic' : string,
  'question' : string,
  'isAdminAdded' : boolean,
  'correctIndex' : bigint,
  'explanation' : string,
  'optionA' : string,
  'optionB' : string,
  'optionC' : string,
  'optionD' : string,
}
export interface QuizResult {
  'id' : bigint,
  'topic' : string,
  'total' : bigint,
  'wrongQuestionIds' : Array<bigint>,
  'score' : bigint,
  'timestamp' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'studentId' : [] | [string],
  'institution' : [] | [string],
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAdminQuestion' : ActorMethod<
    [string, string, string, string, string, bigint, string, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCustomerMessage' : ActorMethod<[bigint], undefined>,
  'deleteProblem' : ActorMethod<[ProblemId], undefined>,
  'deleteQuizQuestion' : ActorMethod<[bigint], undefined>,
  'findProblemsByKeyword' : ActorMethod<[string], Array<Problem>>,
  'findProblemsByType' : ActorMethod<[ProblemType], Array<Problem>>,
  'forceClaimAdmin' : ActorMethod<[], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerMessages' : ActorMethod<[], Array<CustomerMessageWithReply>>,
  'getIsAdmin' : ActorMethod<[], boolean>,
  'getMyCustomerMessages' : ActorMethod<[], Array<CustomerMessageWithReply>>,
  'getProblem' : ActorMethod<[ProblemId], Array<Problem>>,
  'getProblemHistory' : ActorMethod<[], Array<Problem>>,
  'getQuizHistory' : ActorMethod<[], Array<QuizResult>>,
  'getQuizQuestions' : ActorMethod<[[] | [string]], Array<QuizQuestion>>,
  'getUserCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listProblemTypes' : ActorMethod<[], Array<string>>,
  'registerUser' : ActorMethod<[], undefined>,
  'replyToCustomerMessage' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveProblem' : ActorMethod<[ProblemType, string, string], undefined>,
  'saveQuizResult' : ActorMethod<
    [string, bigint, bigint, Array<bigint>],
    undefined
  >,
  'submitCustomerMessage' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];