/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProblemId = IDL.Nat;
export const ProblemType = IDL.Variant({
  'trialBalance' : IDL.Null,
  'cashFlowStatement' : IDL.Null,
  'balanceSheet' : IDL.Null,
  'journalEntry' : IDL.Null,
  'incomeStatement' : IDL.Null,
  'ledgerPostings' : IDL.Null,
});
export const Time = IDL.Int;
export const Problem = IDL.Record({
  'id' : ProblemId,
  'type' : ProblemType,
  'jsonInput' : IDL.Text,
  'solution' : IDL.Text,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({
  'studentId' : IDL.Opt(IDL.Text),
  'institution' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteProblem' : IDL.Func([ProblemId], [], []),
  'findProblemsByKeyword' : IDL.Func([IDL.Text], [IDL.Vec(Problem)], ['query']),
  'findProblemsByType' : IDL.Func([ProblemType], [IDL.Vec(Problem)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProblem' : IDL.Func([ProblemId], [IDL.Vec(Problem)], ['query']),
  'getProblemHistory' : IDL.Func([], [IDL.Vec(Problem)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listProblemTypes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveProblem' : IDL.Func([ProblemType, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProblemId = IDL.Nat;
  const ProblemType = IDL.Variant({
    'trialBalance' : IDL.Null,
    'cashFlowStatement' : IDL.Null,
    'balanceSheet' : IDL.Null,
    'journalEntry' : IDL.Null,
    'incomeStatement' : IDL.Null,
    'ledgerPostings' : IDL.Null,
  });
  const Time = IDL.Int;
  const Problem = IDL.Record({
    'id' : ProblemId,
    'type' : ProblemType,
    'jsonInput' : IDL.Text,
    'solution' : IDL.Text,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'studentId' : IDL.Opt(IDL.Text),
    'institution' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteProblem' : IDL.Func([ProblemId], [], []),
    'findProblemsByKeyword' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Problem)],
        ['query'],
      ),
    'findProblemsByType' : IDL.Func(
        [ProblemType],
        [IDL.Vec(Problem)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProblem' : IDL.Func([ProblemId], [IDL.Vec(Problem)], ['query']),
    'getProblemHistory' : IDL.Func([], [IDL.Vec(Problem)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listProblemTypes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveProblem' : IDL.Func([ProblemType, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };