/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface QuizQuestion {
    id: bigint;
    topic: string;
    question: string;
    isAdminAdded: boolean;
    correctIndex: bigint;
    explanation: string;
    optionA: string;
    optionB: string;
    optionC: string;
    optionD: string;
}
export interface Problem {
    id: ProblemId;
    type: ProblemType;
    jsonInput: string;
    solution: string;
    timestamp: Time;
}
export interface QuizResult {
    id: bigint;
    topic: string;
    total: bigint;
    wrongQuestionIds: Array<bigint>;
    score: bigint;
    timestamp: Time;
}
export type ProblemId = bigint;
export interface CustomerMessageWithReply {
    id: bigint;
    adminReply?: string;
    sender: Principal;
    message: string;
    timestamp: Time;
    senderName: string;
}
export interface UserProfile {
    studentId?: string;
    institution?: string;
    name: string;
}
export enum ProblemType {
    trialBalance = "trialBalance",
    cashFlowStatement = "cashFlowStatement",
    balanceSheet = "balanceSheet",
    journalEntry = "journalEntry",
    incomeStatement = "incomeStatement",
    ledgerPostings = "ledgerPostings"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAdminQuestion(question: string, optionA: string, optionB: string, optionC: string, optionD: string, correctIndex: bigint, topic: string, explanation: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteCustomerMessage(messageId: bigint): Promise<void>;
    deleteProblem(problemId: ProblemId): Promise<void>;
    deleteQuizQuestion(id: bigint): Promise<void>;
    findProblemsByKeyword(keyword: string): Promise<Array<Problem>>;
    findProblemsByType(type: ProblemType): Promise<Array<Problem>>;
    forceClaimAdmin(): Promise<boolean>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomerMessages(): Promise<Array<CustomerMessageWithReply>>;
    getIsAdmin(): Promise<boolean>;
    getMyCustomerMessages(): Promise<Array<CustomerMessageWithReply>>;
    getProblem(problemId: ProblemId): Promise<Array<Problem>>;
    getProblemHistory(): Promise<Array<Problem>>;
    getQuizHistory(): Promise<Array<QuizResult>>;
    getQuizQuestions(topic: string | null): Promise<Array<QuizQuestion>>;
    getUserCount(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listProblemTypes(): Promise<Array<string>>;
    registerUser(): Promise<void>;
    replyToCustomerMessage(messageId: bigint, replyText: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveProblem(type: ProblemType, jsonInput: string, solution: string): Promise<void>;
    saveQuizResult(topic: string, score: bigint, total: bigint, wrongQuestionIds: Array<bigint>): Promise<void>;
    submitCustomerMessage(senderName: string, message: string): Promise<void>;
}
import type { CustomerMessageWithReply as _CustomerMessageWithReply, Problem as _Problem, ProblemId as _ProblemId, ProblemType as _ProblemType, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAdminQuestion(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: string, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdminQuestion(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdminQuestion(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteCustomerMessage(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomerMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomerMessage(arg0);
            return result;
        }
    }
    async deleteProblem(arg0: ProblemId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProblem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProblem(arg0);
            return result;
        }
    }
    async deleteQuizQuestion(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuizQuestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuizQuestion(arg0);
            return result;
        }
    }
    async findProblemsByKeyword(arg0: string): Promise<Array<Problem>> {
        if (this.processError) {
            try {
                const result = await this.actor.findProblemsByKeyword(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findProblemsByKeyword(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async findProblemsByType(arg0: ProblemType): Promise<Array<Problem>> {
        if (this.processError) {
            try {
                const result = await this.actor.findProblemsByType(to_candid_ProblemType_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findProblemsByType(to_candid_ProblemType_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async forceClaimAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.forceClaimAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.forceClaimAdmin();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerMessages(): Promise<Array<CustomerMessageWithReply>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerMessages();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerMessages();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIsAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getIsAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIsAdmin();
            return result;
        }
    }
    async getMyCustomerMessages(): Promise<Array<CustomerMessageWithReply>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCustomerMessages();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCustomerMessages();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProblem(arg0: ProblemId): Promise<Array<Problem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProblem(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProblem(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProblemHistory(): Promise<Array<Problem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProblemHistory();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProblemHistory();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuizHistory(): Promise<Array<QuizResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizHistory();
            return result;
        }
    }
    async getQuizQuestions(arg0: string | null): Promise<Array<QuizQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizQuestions(to_candid_opt_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizQuestions(to_candid_opt_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getUserCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserCount();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listProblemTypes(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProblemTypes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProblemTypes();
            return result;
        }
    }
    async registerUser(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser();
            return result;
        }
    }
    async replyToCustomerMessage(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.replyToCustomerMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.replyToCustomerMessage(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveProblem(arg0: ProblemType, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProblem(to_candid_ProblemType_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProblem(to_candid_ProblemType_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async saveQuizResult(arg0: string, arg1: bigint, arg2: bigint, arg3: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveQuizResult(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveQuizResult(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async submitCustomerMessage(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitCustomerMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitCustomerMessage(arg0, arg1);
            return result;
        }
    }
}
function from_candid_CustomerMessageWithReply_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomerMessageWithReply): CustomerMessageWithReply {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_ProblemType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProblemType): ProblemType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Problem_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Problem): Problem {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId: [] | [string];
    institution: [] | [string];
    name: string;
}): {
    studentId?: string;
    institution?: string;
    name: string;
} {
    return {
        studentId: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.studentId)),
        institution: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.institution)),
        name: value.name
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    adminReply: [] | [string];
    sender: Principal;
    message: string;
    timestamp: _Time;
    senderName: string;
}): {
    id: bigint;
    adminReply?: string;
    sender: Principal;
    message: string;
    timestamp: Time;
    senderName: string;
} {
    return {
        id: value.id,
        adminReply: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.adminReply)),
        sender: value.sender,
        message: value.message,
        timestamp: value.timestamp,
        senderName: value.senderName
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProblemId;
    type: _ProblemType;
    jsonInput: string;
    solution: string;
    timestamp: _Time;
}): {
    id: ProblemId;
    type: ProblemType;
    jsonInput: string;
    solution: string;
    timestamp: Time;
} {
    return {
        id: value.id,
        type: from_candid_ProblemType_n6(_uploadFile, _downloadFile, value.type),
        jsonInput: value.jsonInput,
        solution: value.solution,
        timestamp: value.timestamp
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trialBalance: null;
} | {
    cashFlowStatement: null;
} | {
    balanceSheet: null;
} | {
    journalEntry: null;
} | {
    incomeStatement: null;
} | {
    ledgerPostings: null;
}): ProblemType {
    return "trialBalance" in value ? ProblemType.trialBalance : "cashFlowStatement" in value ? ProblemType.cashFlowStatement : "balanceSheet" in value ? ProblemType.balanceSheet : "journalEntry" in value ? ProblemType.journalEntry : "incomeStatement" in value ? ProblemType.incomeStatement : "ledgerPostings" in value ? ProblemType.ledgerPostings : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CustomerMessageWithReply>): Array<CustomerMessageWithReply> {
    return value.map((x)=>from_candid_CustomerMessageWithReply_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Problem>): Array<Problem> {
    return value.map((x)=>from_candid_Problem_n4(_uploadFile, _downloadFile, x));
}
function to_candid_ProblemType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProblemType): _ProblemType {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId?: string;
    institution?: string;
    name: string;
}): {
    studentId: [] | [string];
    institution: [] | [string];
    name: string;
} {
    return {
        studentId: value.studentId ? candid_some(value.studentId) : candid_none(),
        institution: value.institution ? candid_some(value.institution) : candid_none(),
        name: value.name
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProblemType): {
    trialBalance: null;
} | {
    cashFlowStatement: null;
} | {
    balanceSheet: null;
} | {
    journalEntry: null;
} | {
    incomeStatement: null;
} | {
    ledgerPostings: null;
} {
    return value == ProblemType.trialBalance ? {
        trialBalance: null
    } : value == ProblemType.cashFlowStatement ? {
        cashFlowStatement: null
    } : value == ProblemType.balanceSheet ? {
        balanceSheet: null
    } : value == ProblemType.journalEntry ? {
        journalEntry: null
    } : value == ProblemType.incomeStatement ? {
        incomeStatement: null
    } : value == ProblemType.ledgerPostings ? {
        ledgerPostings: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
